### ISSUE TITLE
[BUG] Error at startup ComputeConvolution

### ISSUE THREAD

**Issue by nedfreetoplay** [deccer/EngineKit#3]
![image](https://user-images.githubusercontent.com/22248940/205530833-d4673ad8-4182-46db-a49e-81f0ce21c16c.png)

**Comment by deccer** [comment]
This is also a known issue, when shutting down, you end up getting exceptions.

**Comment by nedfreetoplay** [comment]
I'd rather leave this problem open until it is solved.

**Comment by deccer** [comment]
I believe that has been fixed.
