### ISSUE TITLE
[BUG] Error at startup DeferredRendering

### ISSUE THREAD

**Issue by nedfreetoplay** [deccer/EngineKit#4]
![image](https://user-images.githubusercontent.com/22248940/205531380-057cfe9e-753f-4e60-978f-493105e989c6.png)
NVIDIA GeForce GTX 1660 | Driver 526.86
AMD Ryzen 7 1700 Eight-Core Processor | Driver 10.0.19041.2251
Visual Studio Community 2022 (x64) 17.4.2
Microsoft .NET Framework 4.8.04084

**Comment by deccer** [comment]
Yup examples are not properly setup and incomplete

**Comment by nedfreetoplay** [comment]
Is that a problem on your part?

**Comment by deccer** [comment]
Yes, Deferred is not setup at all, maybe i should remove these examples for the time being

**Comment by nedfreetoplay** [comment]
It is better to add a Readme and indicate that the examples do not work.

**Comment by deccer** [comment]
Yep, Readme of how to use this hole thing is also a todo...
