### ISSUE TITLE
[BUG] When exiting the Swapchain, the process does not respond.

### ISSUE THREAD

**Issue by nedfreetoplay** [deccer/EngineKit#5]
![image](https://user-images.githubusercontent.com/22248940/205531566-0bfbe649-b7de-45f3-8956-4a24aa98ef3c.png)
Trying to exit via Key Escape and the Quit GUI button.
Five minutes later, she still didn't answer.

**Comment by deccer** [comment]
I believe those errors are all related, could be a binding error in my EngineKit.Native.OpenGL bindings
